- internal/enums/event_outcome.go
- internal/enums/event_outcome_enum.go
EventOutcome enum must match the PreprocessingTaskOutcome enum from Enduro, which was modified in artefactual-sdps/enduro/pull/975.
> Match PreprocessingTaskOutcome enum from Enduro

- internal/activities/add_premis_event.go
- internal/activities/add_premis_event_test.go
- internal/activities/validate_file_formats.go
- internal/activities/validate_file_formats_test.go
- internal/premis/premis.go
- internal/premis/premis_test.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
* Removed redundant PREMIS event for validate file formats
* Correct use of improper PREMIS event types
* Allow PREMIS evebt details and PREMIS event outcome detail to be specified rather than generated
* Add PREMIS event outcome detail specification to PREMIS events in workflow and validate file formats activity
* Generate error when attempting to add a PREMIS event to a non-existent PREMIS object
* Fixed issue with validate formats activity
* Removed unneeded code in tests for add PREMIS event activity
> Fixes to PREMIS event recording

- internal/activities/identify_sip.go
- internal/activities/identify_sip_test.go
- internal/activities/transform_sip_test.go
- internal/activities/validate_structure_test.go
- internal/enums/sip_type.go
- internal/enums/sip_type_enum.go
- internal/fsutil/fsutil.go
- internal/fsutil/fsutil_test.go
- internal/sip/sip.go
- internal/sip/sip_test.go
- internal/workflow/preprocessing_test.go
Fixes #34.
- Add "born digital" SIP type and add it to the "identify SIP" activity,
- Replace "Vecteur" with "digitized" for SIP types
> Add "born digital" SIP type

- internal/activities/verify_manifest.go
- internal/activities/verify_manifest_test.go
- internal/premis/premis.go
Refs #35
- Add the SIP "header" directory to the files checked against the manifest
- Add an exception to ignore the "header/metadata.xml" file when it's not included in the manifest (digitized SIP, born digital)
- Add a unit test that verifies a digitized SIP manifest
> Verify the SIP header files match the manifest

- internal/activities/add_premis_objects.go
- internal/activities/add_premis_objects_test.go
- internal/activities/validate_file_formats.go
- internal/activities/validate_file_formats_test.go
- internal/premis/premis.go
- internal/premis/premis_test.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
Added support for born digital SIPs to PREMIS event recording.
> Fix born digital SIP PREMIS event recording (#19)

- internal/sip/sip.go
- internal/sip/sip_test.go
Use case-insensitive match to find "vecteur" in the SIP path.
Refs #34.
> Tweak DigitizedSIP identification

- internal/activities/add_premis_event.go
- internal/activities/validate_file_formats.go
- internal/activities/validate_file_formats_test.go
- internal/premis/premis.go
- internal/premis/premis_test.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
Fixes #32.
Don't create the premis.xml file until after all validation activities have completed successfully. If validation is unsuccessful the premis.xml file is discarded with the rest of the working SIP, so any writes are lost anyway.
> Write premis.xml file only if validation succeeds

- cmd/worker/workercmd/cmd.go
- internal/activities/add_premis_objects.go
- internal/activities/add_premis_objects_test.go
- internal/activities/transform_sip.go
- internal/activities/verify_manifest.go
- internal/activities/write_identifier_file.go
- internal/activities/write_identifier_file_test.go
- internal/identifiers/identifiers.go
- internal/identifiers/identifiers_test.go
- internal/manifest/manifest.go
- internal/manifest/manifest_test.go
- internal/pips/pips.go
- internal/pips/pips_test.go
- internal/sip/sip.go
- internal/sip/sip_test.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
Fixes #53.
- Parse manifest datei "id" attributes
- Write the "id" values to an "identifiers.json" file in the metadata directory of the SIP
- Archivematica will add the file IDs from the identifiers.json file to the PREMIS object data in the METS file
> Write file IDs to an identifiers.json file

- Makefile
Reduce the noise from gosec when running `make pre-commit`.
> Reduce gosec verbosity in `make pre-commit`

- internal/activities/add_premis_objects_test.go
- internal/activities/transform_sip.go
- internal/activities/transform_sip_test.go
- internal/activities/validate_structure.go
- internal/activities/validate_structure_test.go
- internal/activities/write_identifier_file_test.go
- internal/pips/pips.go
- internal/pips/pips_test.go
- internal/premis/premis.go
- internal/premis/premis_test.go
- internal/sip/sip.go
Fixes #58
Digitized (Vecteur) SIPs are the only type of SIP that contain a Prozess_Digitalisierung_PREMIS.xml file, and they will only ever contain a single dossier.  Because digitized SIPs only have a single dossier that contains a single Prozess_Digitalisierung_PREMIS.xml file there's no need to rename the file in the PIP to avoid name clashes.
Changes:
- Update the SIP identification logic - if a SIP has a Prozess_Digitalisierung_PREMIS.xml file then it must be a digitized SIP
- Add a SIP validation check to confirm that digitized SIPs only contain a single dossier
- Remove the SIP transformation code that renamed the Prozess_Digitalisierung_PREMIS.xml file
> Don't rename Prozess_Digitalisierung_PREMIS.xml

- go.mod
- go.sum
- internal/ais/combinemd.go
- internal/ais/combinemd_test.go
- internal/ais/workflow.go
- internal/ais/workflow_test.go
Fixes #77.
Concatenate the Arelda metadata file from the original package and the METS file created by Archivematica into a single "AIS" metadata file.
> Add an activity to merge AIS metadata files

- internal/ais/combinemd.go
- internal/ais/workflow_test.go
Refs #77.
- Remove extraneous `filepath.Join()` calls
- Improve commentary a bit
- Correct "search_md" zip name in workflow tests
> Minor fixes to AIS workflow

- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
This MR will remove the absolute path from the `Validate SIP metadata activity`. 
Continuation of: https://github.com/artefactual-sdps/preprocessing-sfa/issues/59#issuecomment-2460199726
Previously:   
Now:
> Remove SIP path from SIP metadata validation

- internal/activities/verify_manifest.go
- internal/activities/verify_manifest_test.go
Added support for SHA-1, SHA-256, and SHA-512 file checksums.
Refs #88.
> Support more checksum algorithms (#88)

- cmd/worker/workercmd/cmd.go
- go.mod
Create/clean bagit-gython validator and register bagvalidate activity in the preprocessing worker command.
Refs #93.
**Important!**
**This should make Bag validation work in systems using glibc but it won't work in the Alpine based image used locally. I'll address this issue in a different PR, for now Bags will fail on validation, other SIP formats should work as expected locally too.**
> Register bagvalidate activity

- Dockerfile
- hack/kube/overlays/enduro/preprocessing-secret.yaml
The `bagit-gython` library requires a system based on `glibc` while
Alpine uses `musl`. Change installation of JRE as the one from the
veraPDF CLI image is also based on `musl`.
> Switch to a debian-slim base image

- internal/activities/validate_structure.go
- internal/activities/validate_structure_test.go
Added logic to the validate SIP structure activity to detect empty directories and fail validation if they exist.
> Fail structure validation if any directory is empty

- internal/activities/validate_structure.go
- internal/activities/validate_structure_test.go
Added logic to validate structure to return validation errors if a file or directory's name contains characters incompatible with Archivematica.
> Detect invalid characters in file/directory names

- internal/activities/validate_structure.go
- internal/activities/validate_structure_test.go
When failing structure validation due to empty directories advise user to remove references to the empty directories from their metadata manifest files.
> Improve empty directory errors

- internal/activities/validate_structure.go
- internal/activities/validate_structure_test.go
Made invalid character, for top-level directory name, more user-friendly.
> Improve invalid character errors (#109)

- cmd/worker/workercmd/cmd.go
- internal/fvalidate/fake/mock_validator.go
- internal/fvalidate/fvalidate.go
- internal/fvalidate/verapdf_validator.go
- internal/fvalidate/verapdf_validator_test.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
Execute the veraPDF command, when starting the worker, to get the current veraPDF version so it can be used when recording PREMIS events.
> Get veraPDF version dynamically

- cmd/worker/aiscmd/cmd.go
- internal/ais/workflow.go
- internal/ais/workflow_test.go
Use the AIS `RegisterActivities()` function to register activities in the AIS workflow code and tests.
> Remove duplicate AIS activity registration

- cmd/worker/workercmd/cmd.go
- internal/activities/add_premis_validation_event.go
- internal/activities/add_premis_validation_event_test.go
- internal/activities/validate_files.go
- internal/fformat/fformat.go
- internal/fformat/fformat_test.go
- internal/fvalidate/verapdf_validator.go
- internal/fvalidate/verapdf_validator_test.go
- internal/premis/premis.go
- internal/workflow/preprocessing.go
- internal/workflow/preprocessing_test.go
File validators only check certain types of files. Added activity to only add PREMIS events for files that have actually been checked by a validator.
> Don't add inapplicable veraPDF PREMIS events (#122)

- cmd/worker/workercmd/cmd.go
- internal/activities/validate_files.go
- internal/activities/validate_files_test.go
- internal/fvalidate/errors.go
- internal/fvalidate/errors_test.go
- internal/fvalidate/verapdf_validator.go
- internal/fvalidate/verapdf_validator_test.go
- internal/workflow/preprocessing_test.go
This change was prompted by work on #152, but is mostly unrelated.
I've simplified the `NewVeraPDFValidator` constructor by removing the `runFunc` and `logger` parameters.
The `runFunc` parameter was solely used to avoid the dependency on the veraPDF Java executable in test, but didn't provide any assurance that the code would run correctly in production.
The `logger` parameter was used to log the exit code and STDERR when the veraPDF executable returned an unexpected error code. Rather than logging the veraPDF error data directly, the new code returns a custom `SystemError` that includes the validator name, exit code, STDERR message, and a human readable message intended for display in the Enduro UI.
> Simplify veraPDF validator creation

- internal/activities/validate_files.go
- internal/activities/validate_files_test.go
- internal/fvalidate/errors_test.go
- internal/fvalidate/fake/mock_validator.go
- internal/fvalidate/fvalidate.go
- internal/fvalidate/verapdf_validator.go
- internal/fvalidate/verapdf_validator_test.go
This was prompted by work on #152 but is mostly unrelated.
This change recognizes that veraPDFValidator operates on a directory, rather than an individual file, while allowing for future validators that operate on a single file.
The added `fvalidate.Scope()` method returns the intended scope of the `Validate()` method, either a single file or a directory of files.
The added 'veraPDFValidator.scope' property indicates that the validator operates on a directory of files.
> Add file validator scope
